## Python built-in data structures - to collect multiple data in a structure
    A way to oranginse the data in a structured way

#### Types of bulit-in data structures
*    List -[]
*    Tuples -()
*    Sets - {}
*    Dictionary - key & Value pairs{key:value}

In [17]:
a = 9,98
a             # by default the values are taken in tuple

(9, 98)

## 1. List - []
- allows duplicate
- allows mixed types in the list
- 1 Dimensional
- mutable --> the values can be changed by accessing the index value
- can access data via indexing
  * forward accessing starts with index 0
  * backward accessing starts with index -1

In [1]:
 empty_cart =[]

In [2]:
empty_cart

[]

In [3]:
type(empty_cart)

list

In [4]:
list_toBuy=["apple","orange","Mango","Apple","Banana",9,7.0,66,99]

In [5]:
list_toBuy

['apple', 'orange', 'Mango', 'Apple', 'Banana', 9, 7.0, 66, 99]

In [6]:
list_toBuy[0]

'apple'

In [7]:
list_toBuy[-1]

99

In [8]:
list_toBuy[0:3]

['apple', 'orange', 'Mango']

In [9]:
list_toBuy[:3]

['apple', 'orange', 'Mango']

In [10]:
list_toBuy[3:]

['Apple', 'Banana', 9, 7.0, 66, 99]

In [16]:
list_toBuy[-6:-1]

['Apple', 'Banana', 9, 7.0, 66]

In [17]:
list_toBuy[4]="muskmelon"

In [18]:
list_toBuy

['apple', 'orange', 'Mango', 'Apple', 'muskmelon', 9, 7.0, 66, 99]

## 2. Set - {}
* 1D
* indexing and silicing is not applicable
* mutable
* allows all kinda datatypes

In [7]:
# empty set
empty_cart_set = set()

In [8]:
empty_cart_set

set()

In [9]:
items_tobuy_set= {"apple","orange","Mango","apple","Banana",9,7.0,66,99}
items_tobuy_set

{66, 7.0, 9, 99, 'Banana', 'Mango', 'apple', 'orange'}

In [10]:
items_tobuy_set.add("berry")

In [73]:
items_tobuy_set

{7.0, 9, 99, 'Banana', 'Mango', 'apple', 'berry', 'orange'}

In [68]:
items_tobuy_set.pop()

66

In [75]:
items_tobuy_set.pop()

99

In [11]:
items_tobuy_set[0]

TypeError: 'set' object is not subscriptable

## 3. Tuple - ()
1. 1d
2. allow duplicate
3. allow all datatype
4. indexing and slicing possible
5. immutable - values cannot be changed once assigned

In [1]:
empty_cart_tuple=() #empty_tuple

In [2]:
items_tobuy_tuple =("apple","orange","Mango","apple","Banana",9,7.0,66,99)

In [3]:
items_tobuy_tuple

('apple', 'orange', 'Mango', 'apple', 'Banana', 9, 7.0, 66, 99)

In [11]:
items_tobuy_tuple[-5:]

('Banana', 9, 7.0, 66, 99)

In [5]:
items_tobuy_tuple[4]

'Banana'

In [6]:
items_tobuy_tuple.count("apple")

2

In [7]:
items_tobuy_tuple.index("Banana")

4

In [6]:
items_tobuy_tuple[0]

'apple'

In [15]:
items_tobuy_tuple[0]="strawberry"

TypeError: 'tuple' object does not support item assignment

## Dictionary - {}
1. key : value pair
2. indexing and silicing is not possible
3. mutable
4. it allows duplicate values and the key must be unique
5. allows all datatypes
6. 2D

In [12]:
empty_cart_dict={} #empty dictionary

In [13]:
type(empty_cart_dict)

dict

In [14]:
empty_cart_dict

{}

In [12]:
items_tobuy_dict ={"Math":100, "science":99, "Computer_Science":99}

In [45]:
items_tobuy_dict

{'Math': 75, 'science': 99, 'Computer_Science': 99}

In [19]:
items_tobuy_dict.keys()

dict_keys(['Math', 'science', 'Computer_Science'])

In [23]:
items_tobuy_dict.values()

dict_values([100, 99, 99])

In [14]:
items_tobuy_dict.get("Math")

75

In [13]:
items_tobuy_dict["Math"]= 75

In [40]:
# List
student_mark_dict = {"Name":["Amritha","Harish","Jhon","Jai","Riya"],
                     "Math" : [90,60,70,30,100],
                     "Science":[100,70,90,68,30]
                    }

In [30]:
import pandas as pd

In [32]:
pd.DataFrame(data=items_tobuy_dict)

ValueError: If using all scalar values, you must pass an index

In [41]:
pd.DataFrame(data=student_mark_dict)

      Name  Math  Science
0  Amritha    90      100
1   Harish    60       70
2     Jhon    70       90
3      Jai    30       68
4     Riya   100       30

## task - use 3 ds in dictionary using dataframe

In [56]:
#tuple

patients_id_Dict = {"Name":("Amritha","Riya","Jhon","Jai","Riya"),
                        "Id":(48,50,80,60,50)
                       }
patients_id_Dict

{'Name': ('Amritha', 'Riya', 'Jhon', 'Jai', 'Riya'),
 'Id': (48, 50, 80, 60, 50)}

In [48]:
pd.DataFrame(data=patients_id_Dict)

      Name  Id
0  Amritha  48
1     Riya  50
2     Jhon  80
3      Jai  60
4     Riya  50

In [78]:
# list with dictionary kv pair in set
patients = [
    {"Name": "Amritha", "Age": 18},
    {"Name": "biya", "Age": 20},
    {"Name": "chon", "Age": 30},
    {"Name": "dai", "Age": 40},
    {"Name": "eiya", "Age": 50}
]

df = pd.DataFrame(patients)
df

      Name  Age
0  Amritha   18
1     biya   20
2     chon   30
3      dai   40
4     eiya   50

## The End!!