## Top 8 function in python for data analytics
1. groupby
2. pivot table
3. aggregate
4. cross tab
5. concat
6. apply
7. lamda
8. del (keyword)

## 1. group by

In [1]:
import pandas as pd

In [2]:
insurance_details = pd.read_csv("insurance.csv")
insurance_details

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### averg ins charge region vise

In [3]:
insurance_details.groupby(by = "region")["charges"].mean().round().sort_values()

region
southwest    12347.0
northwest    12418.0
northeast    13406.0
southeast    14735.0
Name: charges, dtype: float64

In [4]:
insurance_details.groupby(by = ["region","sex"])["charges"].mean().round().sort_values()

region     sex
southwest  female    11274.0
northwest  male      12354.0
           female    12480.0
northeast  female    12953.0
southwest  male      13413.0
southeast  female    13500.0
northeast  male      13854.0
southeast  male      15880.0
Name: charges, dtype: float64

## 2. Pivot Table
Pivot tables in pandas let you summarize, group, and reshape your DataFrame—similar to Excel pivot tables but fully programmable. They are ideal when you want categories on rows and columns with aggregated values in the cells.

In [18]:
pd.pivot_table(data = insurance_details,values="charges",index = "region", columns = ["sex",'children'])

sex              female                                            \
children              0             1             2             3
region
northeast   9789.822330  17124.689856  14523.222213  13730.098756
northwest  12583.872074  11118.855757  13127.592952  13430.708082
southeast  14862.013008   9869.908240  11766.313671  19722.982900
southwest  10149.745507  10841.643945  16230.264372   8438.736294

sex                                           male                \
children              4            5             0             1
region
northeast  14542.416663          NaN  13389.637372  15474.289174
northwest  11024.418200   8965.79575   9812.969532   9515.042120
southeast  18267.100687   9923.88820  13791.806750  17424.652082
southwest  10945.677243  10023.64775  13727.264465   9971.325962

sex
children              2             3             4             5
region
northeast  12317.910591  14935.224532  14442.275463   6978.973483
northwest  13762.553939  22971.223279  11508.318988           NaN
southeast  18647.954693  17101.818726   8726.908900  10306.994883
southwest  18875.953545  12071.592329  17923.948000   6864.669500

## 3. Aggregrate

In [25]:
insurance_details.groupby(by = ["region","sex"])["charges"].aggregate(func=["mean","min","max","sum"]).round()

                     mean     min      max        sum
region    sex
northeast female  12953.0  2196.0  58571.0  2085466.0
          male    13854.0  1695.0  48549.0  2258203.0
northwest female  12480.0  2117.0  55135.0  2046699.0
          male    12354.0  1621.0  60021.0  1989013.0
southeast female  13500.0  1608.0  63770.0  2362442.0
          male    15880.0  1122.0  62593.0  3001248.0
southwest female  11274.0  1728.0  48824.0  1826455.0
          male    13413.0  1242.0  52591.0  2186300.0

## 4. CrossTab
pandas.crosstab() creates a frequency table (contingency table) that summarizes the relationship between two or more categorical variables. It is ideal when you want quick counts or normalized percentages across categories

In [129]:
pd.crosstab(index = insurance_details["region"],columns=insurance_details["smoker"],margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

In [4]:
insurance_details.age # note

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

## 5. Concat

In [27]:
sales_2017 = pd.read_csv("Sales Transactions_2017.csv")
sales_2018 = pd.read_csv("Sales Transactions_2018.csv")
sales_2019 = pd.read_csv("Sales Transactions_2019.csv")

In [28]:
sales_full_details = pd.concat([sales_2017,sales_2018,sales_2019])
sales_full_details

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

## Data cleaning task

In [29]:
sales_edited_details.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [30]:
# 1. remove duplicates
sales_edited_details = sales_full_details.drop_duplicates()
sales_edited_details

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [31]:
Step 5 :

SyntaxError: invalid syntax (3928670955.py, line 1)

In [32]:
sales_edited_details.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

In [33]:
# dropping unnesscery columns
sales_edited_details=sales_edited_details.copy()
sales_edited_details.drop(columns = ["Voucher","Disc","Voucher Amount"], inplace=True)

In [34]:
sales_edited_details.isna().sum()

Date       204
Party       35
Product    204
Qty        170
Rate       171
Gross      171
dtype: int64

In [38]:
sales_edited_details['Date'] = pd.to_datetime(sales_edited_details['Date'],format='%d/%m/%Y',errors='coerce')
sales_edited_details['Date'] = sales_edited_details["Date"].dt.strftime('%d/%m/%Y') # convert to string of format '%d/%m/%Y'
sales_edited_details['Date'] = pd.to_datetime(sales_edited_details['Date'],format='%d/%m/%Y',errors='coerce')

In [21]:
sales_edited_details['Date'] = pd.to_datetime(sales_edited_details['Date'],format='%d/%m/%Y',errors='coerce') # convert to datetime dtype

In [39]:
sales_edited_details.dtypes

Date       datetime64[ns]
Party              object
Product            object
Qty                object
Rate               object
Gross              object
dtype: object

In [17]:
sales_edited_details

,Date,Party,Product,Qty,Rate,Gross
0,2017-04-01,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00"
1,2017-04-01,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00"
2,2017-04-01,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00"
3,2017-04-01,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00"
4,2017-04-01,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00"
...,...,...,...,...,...,...
19169,2019-10-10,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00"
19170,2019-10-10,K.SRIHARI,10*12 RK,800,8.5,"6,800.00"
19171,2019-10-10,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00"
19174,NaT,NaN,NaN,"99,284.90","175,381.65","2,203,649.50"
19175,NaT,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40"

## 6. Apply

#### Create a new column eligibility criteria where age >20 is eligible else not not eligible

In [5]:
def check_age(age):
    if age > 20:
        return "eligible"
    else:
        return "Not eligible"

In [9]:
insurance_details["eligibility criteria"] = insurance_details["age"].apply(check_age)

In [10]:
insurance_details

,age,sex,bmi,children,smoker,region,charges,eligibility criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible
2,28,male,33.000,3,no,southeast,4449.46200,eligible
3,33,male,22.705,0,no,northwest,21984.47061,eligible
4,32,male,28.880,0,no,northwest,3866.85520,eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible
1336,21,female,25.800,0,no,southwest,2007.94500,eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,eligible

## 7. Lambda

In [13]:
insurance_details["ec2"] = insurance_details["age"].apply(lambda x:"Eligible" if x>20 else "not Eligible")

In [14]:
insurance_details

,age,sex,bmi,children,smoker,region,charges,eligibility criteria,ec2
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible,not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible,not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,eligible,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,eligible,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,eligible,Eligible
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,eligible,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible,not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible,not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,eligible,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,eligible,Eligible

#### explore list comprehension
#### explore map, query, filter

## 8. del

In [16]:
del insurance_details["ec2"]

In [17]:
insurance_details

,age,sex,bmi,children,smoker,region,charges,eligibility criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible
2,28,male,33.000,3,no,southeast,4449.46200,eligible
3,33,male,22.705,0,no,northwest,21984.47061,eligible
4,32,male,28.880,0,no,northwest,3866.85520,eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible
1336,21,female,25.800,0,no,southwest,2007.94500,eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,eligible

In [ ]:
ye