In [25]:
import pandas as pd #To read files
from matplotlib import pyplot as plt # Used for graph data visualization 
import seaborn as sns # Data Visualization Library
from sklearn.linear_model import LinearRegression # supports LinearRegression.You can then create a model, fit it on data, and make predictions.
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score # Linear regression evaluation metrics
import statsmodels.formula.api as smf

import warnings
warnings.filterwarnings("ignore") # to ignore warnings

In [2]:
cars_data = pd.read_csv(filepath_or_buffer = "Cars.csv")
cars_data

     HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

In [3]:
cars_data.isna().sum()

HP     0
MPG    0
VOL    0
SP     0
WT     0
dtype: int64

In [4]:
cars_data.dtypes

HP       int64
MPG    float64
VOL      int64
SP     float64
WT     float64
dtype: object

In [7]:
X = cars_data[["HP","VOL","SP","WT"]]
X

     HP  VOL          SP         WT
0    49   89  104.185353  28.762059
1    55   92  105.461264  30.466833
2    55   92  105.461264  30.193597
3    70   92  113.461264  30.632114
4    53   92  104.461264  29.889149
..  ...  ...         ...        ...
76  322   50  169.598513  16.132947
77  238  115  150.576579  37.923113
78  263   50  151.598513  15.769625
79  295  119  167.944460  39.423099
80  236  107  139.840817  34.948615

[81 rows x 4 columns]

In [8]:
y = cars_data["MPG"]
y

0     53.700681
1     50.013401
2     50.013401
3     45.696322
4     50.504232
        ...
76    36.900000
77    19.197888
78    34.000000
79    19.833733
80    12.101263
Name: MPG, Length: 81, dtype: float64

In [9]:
linear_model = LinearRegression()

In [10]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.20,shuffle=True,random_state=34)

In [11]:
linear_model.fit(X_train,y_train)

LinearRegression()

In [12]:
y_pred_train = linear_model.predict(X_train)
y_pred_train

array([46.75462614, 29.357921  , 40.59531094, 35.55326361, 37.45059013,
       41.68332337, 32.74736225, 38.35204467, 15.7960024 , 40.45702296,
       39.41888236, 37.47703884, 41.42599626, 23.56427857, 41.17403166,
       26.5237502 , 28.78854008, 35.36168615, 34.25957557, 45.49336752,
       28.4717663 , 35.06820535, 37.09928504, 35.15766796, 36.67235696,
       33.15321636, 42.01639762, 27.80720182, 39.307307  , 38.31289001,
       35.40477942, 23.98357674, 20.38133197, 35.57491245, 36.87008928,
       37.67749978, 41.91914635, 38.82344891, 41.18680984, 30.1294102 ,
       26.62411662, 12.83999048, 36.13102051, 37.3420992 , 35.52563974,
       47.2231036 , 34.40109066, 26.95474873, 37.18263291, 37.54744214,
       33.34178579, 22.83470605, 42.72264178, 25.77796412, 38.23393319,
       19.94553155, 21.76768197, 40.92851149, 36.08544444, 46.38165859,
       20.50748319, 37.20180937, 24.76848656, 35.04420344])

In [13]:
y_pred_test = linear_model.predict(X_test)
y_pred_test

array([32.39394585, 33.36020646, 46.7899155 , 38.66601593, 24.47175816,
       28.8901298 , 26.47157047, 39.78131375, 35.4949115 , 34.74024237,
       42.81695793, 41.37820079, 42.31502785, 36.39884247, 25.06481155,
       18.25707928, 42.15044765])

## train evl metrics

In [16]:
mean_absolute_error(y_train,y_pred_train)

3.1298305777220112

In [17]:
mean_squared_error(y_train,y_pred_train)

17.767616779110305

In [18]:
root_mean_squared_error(y_train,y_pred_train)

4.2151650951190875

In [19]:
r2_score(y_train,y_pred_train)

0.7657768244482415

## test evl metrics

In [20]:
mean_absolute_error(y_test,y_pred_test)

3.8856096980629182

In [22]:
mean_squared_error(y_test,y_pred_test)

24.4931887283102

In [23]:
root_mean_squared_error(y_test,y_pred_test)

4.949059378135425

In [24]:
r2_score(y_test,y_pred_test)

0.7674401633557068

In [37]:
linear_stats_model = smf.ols(formula = "MPG ~ HP+VOL+SP+WT", data=cars_data).fit()

In [38]:
print("r2 score:",linear_stats_model.rsquared.round(2),"\nAdjusted r2: ",linear_stats_model.rsquared_adj.round(2))

r2 score: 0.77
Adjusted r2:  0.76

In [39]:
train_data = X_train.join(y_train)
train_data

     HP  VOL          SP         WT        MPG
17   92   50  117.598513  16.194122  39.354094
52  115  124  120.404312  40.398164  29.629936
16   78   91  114.369293  29.535784  42.789909
39  130   92  128.461264  30.115434  31.014131
22   95  101  120.288996  32.675828  38.310606
..  ...  ...         ...        ...        ...
11   92   50  117.598513  15.753535  39.354094
69  245  112  158.300669  37.141733  21.273708
35   90   98  115.013085  31.911223  37.958743
68  165  123  133.312342  40.472042  23.103172
33  102  113  121.392639  37.573290  36.285456

[64 rows x 5 columns]

In [41]:
linear_stats_model_train = smf.ols(formula = "MPG ~ HP+VOL+SP+WT", data=train_data).fit()

In [42]:
print("r2 score train:",linear_stats_model_train.rsquared.round(2),"\nAdjusted r2 train: ",linear_stats_model_train.rsquared_adj.round(2))

r2 score train: 0.77
Adjusted r2 train:  0.75

In [43]:
test_data = X_test.join(y_test)
test_data

     HP  VOL          SP         WT        MPG
59  100  115  115.576579  37.662874  28.860225
49  115  101  118.288996  33.458472  29.629936
7    62   50  102.598513  15.847758  46.716554
27   92   99  119.105055  32.835069  38.411003
74  140  129  121.864163  42.618698  19.086341
61  120  116  117.668550  37.860411  24.609132
64  150  121  128.128401  40.159482  23.605158
12   92   99  122.105055  32.813592  39.354094
44   93  102  114.380966  33.078632  35.643558
30   84  114  113.484609  37.042350  39.431235
0    49   89  104.185353  28.762059  53.700681
15   73   89  111.185353  29.604527  44.652834
3    70   92  113.461264  30.632114  45.696322
48  130   86  127.909442  28.070597  31.014131
78  263   50  151.598513  15.769625  34.000000
77  238  115  150.576579  37.923113  19.197888
1    55   92  105.461264  30.466833  50.013401

In [50]:
test_predictions = linear_stats_model_train.predict(X_test)

In [51]:
r2_score(y_test,test_predictions)

0.7674401633557071

In [60]:
# 1. Use the true test R2 score you calculated in cell
r2_test = 0.767

# 2. Get n (number of test rows) and k (number of features)
n = X_test.shape[0]  # 17
k = X_test.shape[1] # 4

# 3. Calculate True Adjusted R2
true_adj_r2_test = 1 - ((1 - r2_test) * (n - 1)) / (n - k - 1)

print("True Test Adjusted R2:", round(true_adj_r2_test, 4))

True Test Adjusted R2: 0.6893