In [1]:
import pandas as pd
import warnings 
warnings.filterwarnings("ignore")

In [2]:
weather_data=pd.read_csv("environmental_data.csv")
weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [3]:
weather_data.drop(['Unnamed: 0','Temp C'],axis=1,inplace=True)

In [4]:
weather_data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [5]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [6]:
del weather_data["Ozone"]

In [7]:
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4        NaN  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [8]:
weather_data["Weather"].value_counts()

Weather
S     59
C     49
PS    47
Name: count, dtype: int64

In [9]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [18]:
weather_data[weather_data["Weather"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87     82.0  12.0     7   27  2010    86     NaN
93     24.0  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [10]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [11]:
weather_data.groupby("Weather")["Solar.R"].mean()

Weather
C     192.391304
PS    174.347826
S     193.333333
Name: Solar.R, dtype: float64

In [19]:
weather_data["Solar.R"]=weather_data["Solar.R"].fillna(weather_data.groupby("Weather")["Solar.R"].transform(lambda x : x.mean().round()))

In [20]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
95      NaN   6.9     8    4  2010    86     NaN

In [21]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [22]:
weather_data[weather_data["Weather"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87     82.0  12.0     7   27  2010    86     NaN
93     24.0  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [23]:
weather_data.dropna(subset=["Weather"], inplace=True)

In [24]:
weather_data.shape

(155, 7)

In [25]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [26]:
weather_data["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [27]:
weather_data["Month"].replace(to_replace='May',value='5',inplace=True)

In [28]:
weather_data["Month"]=weather_data["Month"].astype(int)

## Data Transformation
- if data is discrete - minmaxscaler, standardscaler, Robustscaler
- if data is continuous - label encoder, onehotencoder

In [34]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [31]:
weather_copy01 = weather_data.copy()

In [33]:
le = LabelEncoder()
weather_copy01["Weather"]=le.fit_transform(weather_copy01["Weather"])
weather_copy01

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [44]:
weather_copy02 = weather_data.copy()

In [45]:
weather_copy01.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

In [46]:
weather_copy02=pd.get_dummies(data=weather_copy02,columns=["Weather"],dtype="int")
weather_copy02

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

In [66]:
weather_copy02.isna().sum()

Solar.R       0
Wind          0
Month         0
Day           0
Year          0
Temp          0
Weather_C     0
Weather_PS    0
Weather_S     0
dtype: int64

In [47]:
weather_copy02.dtypes

Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather_C       int64
Weather_PS      int64
Weather_S       int64
dtype: object

In [76]:
weather_copy03=weather_data.copy()

In [77]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# 1. Initialize the encoder (sparse_output=False gives a numpy array)
ohe = OneHotEncoder(sparse_output=False)

# 2. Fit and transform the Weather column
encoded = ohe.fit_transform(weather_copy03[["Weather"]])

# 3. Create the DataFrame, CRUCIALLY passing the original index
encoded_df = pd.DataFrame(
    encoded, 
    columns=ohe.get_feature_names_out(["Weather"]),
    index=weather_copy03.index  # <--- This aligns the rows perfectly!
)

# 4. Concat them side-by-side
weather_copy03 = pd.concat([weather_copy03, encoded_df], axis=1)

# 5. Drop the original string column since it's now encoded
weather_copy03.drop(columns=["Weather"], inplace=True)

weather_copy03.head()

   Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0    190.0   7.4      5    1  2010    67        0.0         0.0        1.0
1    118.0   8.0      5    2  2010    72        1.0         0.0        0.0
2    149.0  12.6      5    3  2010    74        0.0         1.0        0.0
3    313.0  11.5      5    4  2010    62        0.0         0.0        1.0
4    193.0  14.3      5    5  2010    56        0.0         0.0        1.0

In [81]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [82]:
encoded_df

     Weather_C  Weather_PS  Weather_S
0          0.0         0.0        1.0
1          1.0         0.0        0.0
2          0.0         1.0        0.0
3          0.0         0.0        1.0
4          0.0         0.0        1.0
..         ...         ...        ...
153        1.0         0.0        0.0
154        0.0         1.0        0.0
155        0.0         0.0        1.0
156        0.0         0.0        1.0
157        1.0         0.0        0.0

[155 rows x 3 columns]

In [83]:
ohe.get_feature_names_out(["Weather"])

array(['Weather_C', 'Weather_PS', 'Weather_S'], dtype=object)

In [84]:
weather_copy03.dtypes

Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather_C     float64
Weather_PS    float64
Weather_S     float64
dtype: object

In [75]:
weather_copy03

,Solar.R,Wind,Month,Day,Year,Temp,Weather,Weather_C,Weather_PS,Weather_S
0,190.0,7.4,5.0,1.0,2010.0,67.0,S,0.0,0.0,1.0
1,118.0,8.0,5.0,2.0,2010.0,72.0,C,1.0,0.0,0.0
2,149.0,12.6,5.0,3.0,2010.0,74.0,PS,0.0,1.0,0.0
3,313.0,11.5,5.0,4.0,2010.0,62.0,S,0.0,0.0,1.0
4,193.0,14.3,5.0,5.0,2010.0,56.0,S,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
153,190.0,7.4,5.0,1.0,2010.0,67.0,C,0.0,0.0,1.0
154,193.0,6.9,9.0,26.0,2010.0,70.0,PS,1.0,0.0,0.0
155,145.0,13.2,9.0,27.0,2010.0,77.0,S,NaN,NaN,NaN
156,191.0,14.3,9.0,28.0,2010.0,75.0,S,NaN,NaN,NaN
157,131.0,8.0,9.0,29.0,2010.0,76.0,C,NaN,NaN,NaN